#!/usr/bin/env bash
#
# Commercial-bank host deployment (Bank A).
#
# On the Bank A VM: install the join bundle (from the CB), bring up this bank's
# OWN Fabric peer + CA + chaincode (joining the CB-hosted `settlement` channel),
# start the owner FSC service and the bank portal. Each bank is fully
# self-contained on its own VM.
#
# Usage: ./scripts/deploy-banka.sh
# Env:   SWORNA_CB_HOST          IP of the central-bank VM (required)
#        SWORNA_BANKB_HOST       IP of the Bank B VM (for cross-bank transfers)
set -euo pipefail

BANK_CODE="${BANK_CODE:-001}"
OWNER_NODE="${OWNER_NODE:-owner1}"
OWNER_PORT="${OWNER_PORT:-9200}"
BANK_STAFF="${BANK_STAFF:-banka_admin}"
BANK_NUM=2

SWORNA_CB_HOST="${SWORNA_CB_HOST:?SWORNA_CB_HOST (central-bank VM IP) is required}"
SWORNA_OTHER_BANK_HOST="${SWORNA_OTHER_BANK_HOST:-${SWORNA_BANKB_HOST:-}}"
[ -n "$SWORNA_OTHER_BANK_HOST" ] || {
  echo "ERROR: SWORNA_OTHER_BANK_HOST (or SWORNA_BANKB_HOST) — the Bank B VM IP — is required for cross-bank transfers." >&2
  exit 1
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$ROOT/bin:$PATH"

echo "==> Bank ${BANK_CODE} host — owner node ${OWNER_NODE}"

echo "==> join bundle (wallets + org crypto, generated by the central bank)"
if [ -d "$ROOT/token-services/keys" ]; then
  echo "   keys/ present — skipping bundle install"
else
  echo "   COPY the join bundle from the CB (see scripts/export-join-bundles.sh) into"
  echo "   $ROOT/token-services/keys  then re-run this script."
  exit 1
fi

echo "==> bank Fabric peer + CA + chaincode (joining the CB's settlement channel)"
BANK_NUM=$BANK_NUM ./scripts/bank-network.sh up

echo "==> token engine (owner ${OWNER_NODE})"
cd "$ROOT/token-services"
export SWORNA_CB_HOST SWORNA_OTHER_BANK_HOST
docker compose -f docker-compose.bank.yaml -f docker-compose.bank.net.yaml \
  up -d --build owner${OWNER_NODE##*owner}

echo "==> bank portal"
cd "$ROOT/web"
npm install --silent
(setsid npm run dev > /tmp/sworna-web.log 2>&1 &)

echo
echo "Bank ${BANK_CODE} host ready."
echo "  portal   http://localhost:5173/b/${BANK_CODE}  (login: ${BANK_STAFF} / sworna-bank)"
echo "  owner    http://localhost:${OWNER_PORT}"