#!/usr/bin/env bash
#
# Commercial-bank host deployment (Bank A / Bank B).
#
# On a bank VM: clone the repo, install the bank's join bundle (the idemix
# wallets the CB generated), and start the bank's owner service + its portal.
# The peer/CA/orderer join steps run from the CB host (see DEPLOYMENT.md);
# distributed peer-join is the VM-validated step.
#
# Usage: ./scripts/deploy-bankb.sh        # or deploy-bankb.sh
set -euo pipefail

BANK_CODE="${BANK_CODE:-002}"
OWNER_NODE="${OWNER_NODE:-owner2}"
OWNER_PORT="${OWNER_PORT:-9300}"
BANK_STAFF="${BANK_STAFF:-bankb_admin}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$ROOT/bin:$PATH"

echo "==> Bank ${BANK_CODE} host — owner node ${OWNER_NODE}"

echo "==> install join bundle (wallets generated by the central bank)"
if [ -d "$ROOT/token-services/keys" ]; then
  echo "   keys/ present — skipping bundle install"
else
  echo "   COPY the join bundle (keys/ + confs) from the CB into"
  echo "   $ROOT/token-services/keys  then re-run this script."
  exit 1
fi

echo "==> token engine (owner ${OWNER_NODE})"
cd "$ROOT/token-services"
docker-compose up -d --build owner${OWNER_NODE##*owner}

echo "==> bank portal"
cd "$ROOT/web"
npm install --silent
(setsid npm run dev > /tmp/sworna-web.log 2>&1 &)

echo
echo "Bank ${BANK_CODE} host ready."
echo "  portal   http://localhost:5173/b/${BANK_CODE}  (login: ${BANK_STAFF} / sworna-bank)"
echo "  owner    http://localhost:${OWNER_PORT}"